package io.swagger.api.impl;

import javax.enterprise.context.RequestScoped;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.api.ApiResponseMessage;
import io.swagger.api.NotFoundException;
import io.swagger.api.UsersApiService;
import io.swagger.model.User;

@RequestScoped
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaResteasyServerCodegen", date = "2018-08-06T19:44:40.063-04:00")
public class UsersApiServiceImpl implements UsersApiService {
	// generated by swagger code gen, modified by Anne
	@Override
	public Response usersGet(SecurityContext securityContext) throws NotFoundException {
		// do some magic!
		ObjectMapper mapper = new ObjectMapper();

		try {
			String jsonString = mapper.writeValueAsString(createUsers());
			return Response.ok().entity(new ApiResponseMessage(ApiResponseMessage.OK, jsonString)).build();
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return Response.ok().entity(new ApiResponseMessage(ApiResponseMessage.ERROR, e.getMessage())).build();
		}
	}

	private User[] createUsers() {
		User[] users = new User[3];
		users[0] = createUser(1, "Sonny Rollins", "sonny.rollins@gmail.com", "999-555-1111", "rollins");
		users[1] = createUser(2, "McCoy Tyner", "mccoy.tyner@gmail.com", "999-555-2222", "mccoy");
		users[2] = createUser(3, "Kurt Elling", "kurt.elling@gmail.com", "999-555-3333", "elling");
		return users;
	}

	private User createUser(Integer id, String name, String email, String phone, String username) {
		User u = new User();
		u.setId(id);
		u.setName(name);
		u.setEmail(email);
		u.setPhone(phone);
		u.setUsername(username);
		return u;
	}


}
